### ISSUE TITLE
cannot run pm2 on windows

### ISSUE THREAD

**Issue by rezarajabii** [jscomplete/advanced-react#1]
Hi Samer,

I cannot run pm2 on my machine, It's a windows 7. I get this error every time I try to run "pm2 logs" (I cloned your repository):

Error: spawn babel-node ENOENT
PM2 | at _errnoException (util.js:1022:11)
PM2 | at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
PM2 | at onErrorNT (internal/child_process.js:374:16)
PM2 | at _combinedTickCallback (internal/process/next_tick.js:138:11)
PM2 | at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by boswellgathu** [comment]
@PersianIronwood I saw this https://github.com/babel/babel/issues/4911#issuecomment-278190370, Kind of solved the problem, the explanation is at https://github.com/babel/babel/issues/4911#issuecomment-264743112

I hope this helps

**Comment by samerbuna** [comment]
I have just patched the course with a recommendation to not use PM2 on Windows. Use nodemon instead.
